from __future__ import annotations

from datetime import datetime

from .rag import MarketIntelligenceRetriever
from .services import ForecastService, MarketService


class OutlookOrchestrator:
    """Single-agent workflow boundary; it never computes a price with an LLM."""

    def __init__(
        self,
        forecasts: ForecastService,
        market: MarketService,
        retriever: MarketIntelligenceRetriever,
    ) -> None:
        self.forecasts = forecasts
        self.market = market
        self.retriever = retriever

    def outlook(
        self, as_of: datetime, horizon: int = 20, run_name: str | None = None
    ) -> dict[str, object]:
        forecast = self.forecasts.run_forecast(as_of, [horizon], run_name=run_name)[0]
        snapshot = self.market.snapshot(as_of)
        evidence = self.retriever.search(
            "Henry Hub natural gas storage weather production outlook", as_of, 5
        )
        return {
            "forecast": forecast.to_dict(),
            "current_market_conditions": snapshot,
            "quantitative_drivers": [driver.__dict__ for driver in forecast.drivers],
            "market_evidence": [result.__dict__ for result in evidence],
            "uncertainty": {
                "label": "empirical 80% interval",
                "p10": forecast.p10,
                "p90": forecast.p90,
            },
            "model_historical_performance": forecast.metrics,
            "guardrail": "The numerical forecast was generated by the fitted model, not an LLM.",
        }
